# Generated by Django 3.2.13 on 2022-10-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('profilepic', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
