# Generated by Django 3.2.13 on 2022-10-21 23:59

import django.core.validators
from django.db import migrations, models
import signetorprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('signetorprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(40, 'the field must contain at least 40 characters')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=signetorprofile.models.Profile.images),
        ),
    ]
