# Generated by Django 3.2.13 on 2022-10-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageSender', models.TextField(blank=True, null=True)),
                ('signetoraddress', models.TextField(blank=True, null=True)),
                ('messageId', models.TextField(blank=True, null=True)),
                ('tokenURI', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
