# Generated by Django 3.2.13 on 2022-10-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signetorinfos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signet',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
