# Generated by Django 3.2.13 on 2022-12-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signetorinfos', '0002_signet_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='signet',
            name='liked',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signet',
            name='stared',
            field=models.TextField(blank=True, null=True),
        ),
    ]
