# Generated by Django 3.2.13 on 2022-12-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signetorinfos', '0003_auto_20221220_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signet',
            name='liked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signet',
            name='stared',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
