# Generated by Django 3.2.13 on 2022-12-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signetorinfos', '0004_auto_20221220_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signet',
            name='liked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signet',
            name='stared',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
