# Generated by Django 3.2.13 on 2022-12-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signetorinfos', '0005_auto_20221221_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='signet',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
