# Generated by Django 3.2.13 on 2023-01-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signetorinfos', '0006_signet_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signet',
            name='signetoraddress',
        ),
    ]
