# Generated by Django 3.2.13 on 2022-10-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenurl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenurl',
            name='idnum',
            field=models.TextField(blank=True, null=True),
        ),
    ]
