# Generated by Django 3.2.13 on 2023-01-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenurl', '0003_tokenurl_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenurl',
            name='idnum',
        ),
    ]
