# Generated by Django 3.2.13 on 2022-12-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('messageId', models.IntegerField()),
                ('comments', models.TextField()),
                ('created_on', models.TextField()),
            ],
        ),
    ]
