# Generated by Django 3.2.13 on 2023-01-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='userAddress',
        ),
    ]
