# Generated by Django 3.2.13 on 2022-12-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfNotification', models.TextField()),
                ('userRecived', models.TextField(blank=True, null=True)),
                ('userSend', models.TextField(blank=True, null=True)),
                ('viewd', models.BooleanField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
