# Generated by Django 3.2.13 on 2022-12-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20221220_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='messageId',
            field=models.TextField(blank=True),
        ),
    ]
