# Generated by Django 3.2.13 on 2022-12-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notifications_messageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
