# Generated by Django 3.2.13 on 2022-12-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notifications_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
