# Generated by Django 3.2.13 on 2023-01-11 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(40, 'the field must contain at least 40 characters')])),
                ('name', models.TextField(blank=True, max_length=15, null=True)),
                ('pfp', models.TextField(blank=True, null=True)),
                ('signatrue', models.TextField(blank=True, null=True)),
                ('record', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1960, 'the field must contain at least 2 characters')])),
            ],
        ),
    ]
