# Generated by Django 3.2.13 on 2023-01-11 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signetuserrecord', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='userAddress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pfp',
            new_name='userPfp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='record',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='signatrue',
        ),
        migrations.AddField(
            model_name='profile',
            name='userRecord',
            field=models.TextField(default=1234124312342134, validators=[django.core.validators.MinLengthValidator(1960, 'the field must contain at least 2 characters')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='userSignatrue',
            field=models.TextField(default=12341234),
            preserve_default=False,
        ),
    ]
