# Generated by Django 3.2.13 on 2023-01-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signetuserrecord', '0003_alter_profile_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userBio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
