# Generated by Django 3.2.13 on 2023-01-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signetuserrecord', '0005_profile_useripaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userRegisteredtime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
